[project]
name = "mltg"
version = "0.1.0"
description = "Machine Learning Testground"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "flax==0.12.8",
    "grain==0.2.18",
    "jax[cpu]==0.11.0",
    "marimo==0.23.16",
    "optax==0.2.8",
    "orbax-checkpoint==0.12.2",
    "pydantic-ai-slim[mistral,openai]==2.24.0",
    "scipy==1.18.0",
    "tiktoken==0.13.0",
]

[dependency-groups]
dev = [
    "jupyterlab==4.6.2",
    "matplotlib==3.11.1",
    "pytest==9.1.1",
    "ruff==0.16.1",
    "torchvision==0.28.0",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = ["COM812", "CPY001", "D", "PLR2004", "S101", "T20"]
