name: CI

on:
  push:
    branches:
      - "main"
      - "renovate/**"

  pull_request:
    branches:
      - "main"

  workflow_dispatch:

env:
  PYTHONPATH: mltg

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Install Python
        run: uv python install 3.14

      - name: Setup environment
        run: uv sync

      - name: Check
        run: uv run ruff check

      - name: Test
        run: uv run pytest
